export const CACHE_KEY = {
  REVIEW: {
    GET_ALL: "REVIEW_GET_ALL"
  },
  AUTH: {
    GET_ME: "AUTH_GET_ME"
  },
  CATEGORY: {
    GET_ALL: "CATEGORY_GET_ALL",
    GET_BY_ID: "CATEGORY_GET_BY_ID"
  },

  BRAND: {
    GET_ALL: "BRAND_GET_ALL",
    GET_BY_ID: "BRAND_GET_BY_ID"
  },
  FAQ: {
    GET_ALL: "FAQ_GET_ALL"
  },
  TERM: {
    GET_ALL: "TERM_GET_ALL"
  },
  CARD: {
    GET_ALL: "CARD_GET_ALL"
  },
  PAYMENT_ACCOUNT: {
    GET_ALL: "PAYMENT_ACCOUNT_GET_ALL"
  },
  ADDRESS: {
    GET_ADDRESSES: "ADDRESS_GET_ADDRESSES"
  }
}
