export const CACHE_KEY = {
  REVIEW: {
    GET_ALL: "REVIEW_GET_ALL"
  },
  AUTH: {
    GET_ME: "AUTH_GET_ME"
  },
  CATEGORY: {
    GET_ALL: "CATEGORY_GET_ALL",
    GET_BY_ID: "CATEGORY_GET_BY_ID",
    GET_PRODUCTS: "CATEGORY_GET_PRODUCTS",
    GET_CATEGORY_AND_PRODUCTS: "CATEGORY_GET_CATEGORY_AND_PRODUCTS"
  },

  BRAND: {
    GET_ALL: "BRAND_GET_ALL",
    GET_BY_ID: "BRAND_GET_BY_ID",
    GET_PRODUCTS: "BRAND_GET_PRODUCTS",
    GET_BRAND_AND_PRODUCTS: "BRAND_GET_BRAND_AND_PRODUCTS"
  },
  FAQ: {
    GET_ALL: "FAQ_GET_ALL"
  },
  TERM: {
    GET_ALL: "TERM_GET_ALL"
  },
  CARD: {
    GET_ALL: "CARD_GET_ALL"
  },
  PAYMENT_ACCOUNT: {
    GET_ALL: "PAYMENT_ACCOUNT_GET_ALL"
  },
  ADDRESS: {
    GET_ADDRESSES: "ADDRESS_GET_ADDRESSES"
  },
  PRODUCT: {
    GET_BY_ID: "PRODUCT_GET_BY_ID",
    GET_ALL: "PRODUCT_GET_ALL",
    GET_DRAFT: "PRODUCT_GET_DRAFT",
    GET_POPULAR: "PRODUCT_GET_POPULAR",
    GET_RELATED: "PRODUCT_GET_RELATED",
    GET_RECOMMEND: "PRODUCT_GET_RECOMMEND",
    GET_DISCOUNT: "PRODUCT_GET_DISCOUNT",
    GET_BEST_SELLER: "PRODUCT_GET_BEST_SELLER",
    GET_FEATURED: "PRODUCT_GET_FEATURED",
    GET_COLORS: "PRODUCT_GET_COLORS",
    GET_CUSTOMER_FAVORITE: "PRODUCT_GET_CUSTOMER_FAVORITE"
  },
  COUPONS: {
    GET_ALL: "COUPONS_GET_ALL",
    GET_TODAY: "COUPONS_GET_TODAY"
  },
  QUESTION: {
    GET_PRODUCT_QUESTIONS: "QUESTION_GET_PRODUCT_QUESTIONS"
  },
  ORDER: {
    GET_ALL: "ORDER_GET_ALL",
    GET_BY_ID: "ORDER_GET_BY_ID"
  },
  ORDER_ITEM: {
    GET_ALL: "ORDER_ITEM_GET_ALL"
  },
  PAYMENT_METHODS: {
    GET_ALL: "PAYMENT_METHODS_GET_ALL"
  },
  REFUND_POLICY: {
    GET_ALL: "REFUND_POLICY_GET_ALL"
  }
}
