export enum EResourcePermissions {
  REVIEW = "REVIEW",
  FAVORITE = "FAVORITE",
  PRODUCT = "PRODUCT",
  COUPON = "COUPON",
  ADDRESS = "ADDRESS",
  PRODUCT_ASSET_ATTRIBUTE = "PRODUCT_ASSET_ATTRIBUTE",
  CATEGORY = "CATEGORY",
  ATTRIBUTE = "ATTRIBUTE",
  ASSET = "ASSET",
  MESSAGE = "MESSAGE"
}
